version: 2
registries:
  maven-repository-maven-pkg-github-com-dumbdogdiner-buildtoolspac:
    type: maven-repository
    url: https://maven.pkg.github.com/DumbDogDiner/BuildToolsPackages
    username: vladfrangu
    password: "${{secrets.MAVEN_REPOSITORY_MAVEN_PKG_GITHUB_COM_DUMBDOGDINER_BUILDTOOLSPAC_PASSWORD}}"

updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: weekly
    time: "12:00"
  open-pull-requests-limit: 16
  ignore:
  - dependency-name: org.jetbrains.kotlinx:kotlinx-coroutines-core
    versions:
    - "> 1.3.7, < 1.4"
  - dependency-name: org.jetbrains.kotlin.jvm
    versions:
    - 1.4.21-2
    - 1.4.30
    - 1.4.31
    - 1.4.32
  - dependency-name: org.jetbrains.kotlinx:kotlinx-coroutines-core
    versions:
    - 1.4.2-native-mt
  registries:
  - maven-repository-maven-pkg-github-com-dumbdogdiner-buildtoolspac
